### PR TITLE
Improvements to ZeroConf in order to make it run on iOS16

### PR DESCRIPTION
**Pull request by MarLoe**
Also bumped the C# language version to latest

### CODE REVIEW

**Comment by vhugogarcia** [comment]
I have tested this improvements for iOS 16 and they worked very good. Thanks @MarLoe for the contribution.

@clairernovotny is it possible for you to give us a hand to review it and merge it, so we can get an updated nuget package, please? 

Thanks in advance 🙏🏻

**Comment by retepz** [comment]
Bump?

**Comment by project-x51** [comment]
Bump?

**Comment by clairernovotny** [comment]
Appologies for the delay, I'll try to get this reviewed and merged in the next few days.

**Comment by MarLoe** [comment]
> Appologies for the delay, I'll try to get this reviewed and merged in the next few days.

That sounds amazing. I am using this package actively, as Android does not always provide correct mDNS hostname resolving.

How would you feel about me becoming a collaborator on this project?

**Comment by clairernovotny** [comment]
@MarLoe do we still need this? Do you want to review the latest build? The CI feed always has the latest main build in it as well: `https://pkgs.dev.azure.com/clairernovotny/GitBuilds/_packaging/Zeroconf/nuget/v3/index.json`

**Comment by clairernovotny** [comment]
@MarLoe I'd love to get confirmation that the issue is solved for you before I publish it.

**Comment by MarLoe** [comment]
> @MarLoe I'd love to get confirmation that the issue is solved in the latest CI version before I publish it.

I have tested on iOS18.1 and it seems to be working correctly.

**Review by malo-bo — APPROVED** [review]

**Comment by MarLoe** [comment]
Managed to approve using the "wrong" account. I am @malo-bo as well - just work related 😉

**Comment by clairernovotny** [comment]
Closing as 3.7.16 was just published on NuGet.org.

**Pull request closed without merging**
